### ISSUE TITLE
modify run-rate-values.js to allow for Rate values <1 and exact rate values <1000

### ISSUE THREAD

**Issue by Wallysburg** [catdad/grandma#83]
Since and rate value <1000 will always require an f.numerator = 1, I propose that there be a conditional added to run-rate-values.js to check for rate values < 1000 and return something like this:

```
function rateOfOne(rate) {
    return {
        numerator: 1,
        denominator: parseFloat(((1 / rate) * 1000).toFixed(2)),
    };
}

function perSecond(rate) {
    return new Fraction(rate, 1000);
}

function simplify(fraction) {
    // Do a really rough simplification, making sure
    // that we stay above the requested rate. In almost
    // all cases, this is good enough.
    return new Fraction(
        Math.ceil(fraction.numerator / 2),
        Math.floor(fraction.denominator / 2)
    );
}

function calculateRunValues(rate) {
    var f;
    
    if (rate < 1000) {
        // we won't bother with anything less than 1 per second
        f = rateOfOne(rate);
    } else {
        f = perSecond(rate);
        while (f.denominator > 500 && f.numerator > 1) {
            f = simplify(f);
        }
    }
    console.log(f);
    
    return {
        rate: rate,
        realRate: (f.numerator / f.denominator * 1000),
        // start x amount of tasks
        concurrent: f.numerator,
        // every y milliseconds
        intTime: f.denominator
    };
}

module.exports = calculateRunValues;

```

This solution will work for any rate values <1000, including fractional values.

**Comment by catdad** [comment]
I believe this is the only code you care about:

```javascripr
return {
    numerator: 1,
    denominator: parseFloat(((1 / rate) * 1000).toFixed(2)),
};
```

The problem here is that you are completely missing the point of the fraction simplification. See, both the numerator and denominator have to be integers. The numerator has to be an integer because I cannot start 1.3 tasks. The denominator has to be an integer because timers in JS will always round up. Therefore, the code `setTimeout(func, 3.2)` will execute a timeout of 4 milliseconds.

As an example, I will use the value 437. This comes out to:

```javascript
{
    numerator: 1,
    denominator: 2.29
}
```

When I set a timer of 2.29, it will actually execute a timer of 3, making the rate 333.33 rather than 437. That is 24% lower than the requested rate, which is really bad.

In the latest code in master, the returned fraction would be:

```javascript
{
    numerator: 11,
    denominator: 26
}
```

This results in a real rate of 423.0769230769231, which is only 3% lower. I'd be okay to accept 3 percent.

I know in your use case, you are making requests to a remote server, which will more than certainly cover the difference between 26ms and 2.29ms in terms of the interval between tasks.

**Comment by catdad** [comment]
Also, not sure if you noticed, but in v0.4.1, rates lower than 1 are again allowed.
